In [1]:
import pandas as pd

df = pd.read_csv("../dataset/job_description.csv")
df.head()

,job_role,job_description
0,Data Scientist,"Python, Machine Learning, Deep Learning, SQL, ..."
1,Data Analyst,"SQL, Excel, Power BI, Python, Data Cleaning, D..."
2,Machine Learning Engineer,"Python, TensorFlow, PyTorch, Machine Learning,..."
3,Software Engineer,"Java, DSA, OOP, DBMS, Git, Problem Solving"
4,Web Developer,"HTML, CSS, JavaScript, React, Node.js, Respons..."

In [2]:
def extract_skills(text):
    # Convert to lowercase
    text = text.lower()
    
    # Split by comma
    skills = text.split(",")
    
    # Clean spaces
    skills = [skill.strip() for skill in skills]
    
    return skills

df["job_skills"] = df["job_description"].apply(extract_skills)

df.head()

,job_role,job_description,job_skills
0,Data Scientist,"Python, Machine Learning, Deep Learning, SQL, ...","[python, machine learning, deep learning, sql,..."
1,Data Analyst,"SQL, Excel, Power BI, Python, Data Cleaning, D...","[sql, excel, power bi, python, data cleaning, ..."
2,Machine Learning Engineer,"Python, TensorFlow, PyTorch, Machine Learning,...","[python, tensorflow, pytorch, machine learning..."
3,Software Engineer,"Java, DSA, OOP, DBMS, Git, Problem Solving","[java, dsa, oop, dbms, git, problem solving]"
4,Web Developer,"HTML, CSS, JavaScript, React, Node.js, Respons...","[html, css, javascript, react, node.js, respon..."

In [3]:
df.to_csv("../dataset/job_with_skills.csv", index=False)

print("Job skill extraction completed.")

Job skill extraction completed.

In [4]:
df.to_csv("../dataset/job_with_skills.csv", index=False)

print("Job skill extraction completed.")

Job skill extraction completed.